// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace loadxml.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Schemas.ED807BICDirectoryEntry", b =>
                {
                    b.Property<string>("BIC")
                        .HasColumnType("text");

                    b.HasKey("BIC");

                    b.ToTable("ED807BICDirectoryEntry");
                });

            modelBuilder.Entity("Schemas.ED807BICDirectoryEntryAccounts", b =>
                {
                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<string>("AccountCBRBIC")
                        .HasColumnType("text");

                    b.Property<string>("AccountStatus")
                        .HasColumnType("text");

                    b.Property<string>("CK")
                        .HasColumnType("text");

                    b.Property<string>("DateIn")
                        .HasColumnType("text");

                    b.Property<string>("DateOut")
                        .HasColumnType("text");

                    b.Property<string>("RegulationAccountType")
                        .HasColumnType("text");

                    b.HasKey("Account");

                    b.ToTable("ED807BICDirectoryEntryAccount");
                });

            modelBuilder.Entity("Schemas.ED807BICDirectoryEntryAccountsAccRstrList", b =>
                {
                    b.Property<string>("AccRstr")
                        .HasColumnType("text");

                    b.Property<string>("AccRstrDate")
                        .HasColumnType("text");

                    b.Property<string>("ED807BICDirectoryEntryAccountsAccount")
                        .HasColumnType("text");

                    b.HasKey("AccRstr");

                    b.HasIndex("ED807BICDirectoryEntryAccountsAccount");

                    b.ToTable("ED807BICDirectoryEntryAccountsAccRstrList");
                });

            modelBuilder.Entity("Schemas.ED807BICDirectoryEntryAccountsAccRstrList", b =>
                {
                    b.HasOne("Schemas.ED807BICDirectoryEntryAccounts", null)
                        .WithMany("AccRstrList")
                        .HasForeignKey("ED807BICDirectoryEntryAccountsAccount");
                });

            modelBuilder.Entity("Schemas.ED807BICDirectoryEntryAccounts", b =>
                {
                    b.Navigation("AccRstrList");
                });
#pragma warning restore 612, 618
        }
    }
}
